--Query 1 

SELECT dep.DEPARTMENT_NAME, MAX(emp.SALARY)
FROM DEPARTMENTS dep
INNER JOIN EMPLOYEES emp
ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID 
GROUP BY dep.DEPARTMENT_NAME
ORDER BY MAX(emp.SALARY) DESC;


--Query 2

SELECT DISTINCT emp.EMPLOYEE_ID, emp.FIRST_NAME, emp.LAST_NAME, emp2.FIRST_NAME || ' ' || emp2.LAST_NAME AS "MANAGER_NAME"
FROM EMPLOYEES emp
INNER JOIN JOB_HISTORY his
ON emp.EMPLOYEE_ID = his.EMPLOYEE_ID
INNER JOIN EMPLOYEES emp2
ON emp2.EMPLOYEE_ID = emp.MANAGER_ID
ORDER BY emp.LAST_NAME;


--Query 3

SELECT dep.DEPARTMENT_NAME, ROUND(COALESCE(AVG(emp.SALARY), 0), 2) AS "AVERAGE_DEPARTMENT_SALARY"
FROM DEPARTMENTS dep
LEFT JOIN EMPLOYEES emp
ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID
GROUP BY dep.DEPARTMENT_NAME
ORDER BY COALESCE(AVG(emp.SALARY), 0) DESC, dep.DEPARTMENT_NAME;


--Query 4

SELECT reg.REGION_NAME, COUNT(emp.EMPLOYEE_ID) AS "EMPLOYEE_TOTAL"
FROM REGIONS reg
LEFT JOIN COUNTRIES cou
ON reg.REGION_ID = cou.REGION_ID
LEFT JOIN LOCATIONS loc
ON loc.COUNTRY_ID = cou.COUNTRY_ID
LEFT JOIN DEPARTMENTS dep
ON loc.LOCATION_ID = dep.LOCATION_ID
LEFT JOIN EMPLOYEES emp
ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID 
GROUP BY reg.REGION_NAME
ORDER BY "EMPLOYEE_TOTAL" DESC;



--Query 5 

SELECT emp.EMPLOYEE_ID, emp.FIRST_NAME, emp.LAST_NAME, dep.DEPARTMENT_NAME, emp.SALARY
FROM EMPLOYEES emp
INNER JOIN DEPARTMENTS dep
ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID
WHERE UPPER(dep.DEPARTMENT_NAME)= 'SALES' 
AND SALARY > (SELECT AVG(SALARY) FROM  EMPLOYEES emp
                INNER JOIN DEPARTMENTS dep
                ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID 
                WHERE UPPER(dep.DEPARTMENT_NAME)= 'SALES') 
GROUP BY emp.EMPLOYEE_ID, emp.FIRST_NAME, emp.LAST_NAME, dep.DEPARTMENT_NAME, emp.SALARY
ORDER BY SALARY DESC, LAST_NAME;


--BONUS 1
SELECT NVL(reg.REGION_NAME, '(No Region Available)'), COUNT(emp.EMPLOYEE_ID) AS "EMPLOYEE_TOTAL" 
FROM REGIONS reg
FULL JOIN COUNTRIES cou
ON reg.REGION_ID = cou.REGION_ID
FULL JOIN LOCATIONS loc
ON loc.COUNTRY_ID = cou.COUNTRY_ID
FULL JOIN DEPARTMENTS dep
ON loc.LOCATION_ID = dep.LOCATION_ID
FULL JOIN EMPLOYEES emp
ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID 
GROUP BY reg.REGION_NAME
ORDER BY "EMPLOYEE_TOTAL" DESC;

