CREATE OR REPLACE TRIGGER inv_update_from_rcvchange
  AFTER UPDATE ON SHIPMENT_LINE
  FOR EACH ROW
BEGIN
  IF :OLD.SL_DATE_RECEIVED IS  NOT NULL THEN
    UPDATE INVENTORY
    SET INV_QOH = INV_QOH + :NEW.SL_QUANTITY
    WHERE INV_ID = :OLD.INV_ID;
  ELSIF :NEW.SL_QUANTITY > :OLD.SL_QUANTITY THEN
    UPDATE INVENTORY
    SET INV_QOH = INV_QOH + :NEW.SL_QUANTITY - :OLD.SL_QUANTITY
    WHERE INV_ID = :OLD.INV_ID;
  ELSE
    UPDATE INVENTORY
    SET INV_QOH = INV_QOH - (:OLD.SL_QUANTITY - :NEW.SL_QUANTITY)
    WHERE INV_ID = :OLD.INV_ID;
  END IF;
END;