--------------------------------------------------------
--  File created - Tuesday-May-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARS_CAR_TYPES
--------------------------------------------------------

  CREATE TABLE "CARS"."CARS_CAR_TYPES" 
   (	"CAR_TYPE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CARS_COLORS
--------------------------------------------------------

  CREATE TABLE "CARS"."CARS_COLORS" 
   (	"COLOR" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CARS_NUMBER_OF_DOORS
--------------------------------------------------------

  CREATE TABLE "CARS"."CARS_NUMBER_OF_DOORS" 
   (	"DOORS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CARS.CARS_CAR_TYPES
SET DEFINE OFF;
Insert into CARS.CARS_CAR_TYPES (CAR_TYPE) values ('FORD');
Insert into CARS.CARS_CAR_TYPES (CAR_TYPE) values ('TOYOTA');
Insert into CARS.CARS_CAR_TYPES (CAR_TYPE) values ('VOLKSWAGEN');
Insert into CARS.CARS_CAR_TYPES (CAR_TYPE) values ('CHEVY');
REM INSERTING into CARS.CARS_COLORS
SET DEFINE OFF;
Insert into CARS.CARS_COLORS (COLOR) values ('WHITE');
Insert into CARS.CARS_COLORS (COLOR) values ('RED');
Insert into CARS.CARS_COLORS (COLOR) values ('GREEN');
REM INSERTING into CARS.CARS_NUMBER_OF_DOORS
SET DEFINE OFF;
Insert into CARS.CARS_NUMBER_OF_DOORS (DOORS) values (2);
Insert into CARS.CARS_NUMBER_OF_DOORS (DOORS) values (4);
