SELECT  DISTINCT
Cast(REPORTNAME as varchar(200)) as ReportName,
Cast
	(
	 SUBSTRING
			(
			TEMPREPORTPATH,
			1,
			((CHARINDEX(CHAR(39),TEMPREPORTPATH)-1))
			) as Varchar(300)) AS REPORTPATH,
Cast
	(
	 SUBSTRING
			(
			TEMPSUBJECT,
			CHARINDEX(CHAR(39),TEMPSUBJECT) +1,
			(charindex(char(93),TEMPSUBJECT,2))-(CHARINDEX(CHAR(39),TEMPSUBJECT) +2)
			 ) as varchar(100)) AS [SUBJECT]
FROM
(
SELECT
        SUBSTRING (
				COGIPF_REPORTNAME,
				CHARINDEX(CHAR(39),COGIPF_REPORTNAME) +1,
				((CHARINDEX(CHAR(93),COGIPF_REPORTNAME)-2) -(CHARINDEX(CHAR(39),COGIPF_REPORTNAME)))
		) AS REPORTNAME,
        SUBSTRING(
				COGIPF_REPORTPATH,
				PATINDEX('%]/folder%' ,COGIPF_REPORTPATH),
				PATINDEX('%]/folder%' ,COGIPF_REPORTPATH)
		) AS TEMPSUBJECT,
		SUBSTRING(
				(Replace(COGIPF_REPORTPATH,''']/folder[@name=''','->')),
				(24),
				Len(COGIPF_REPORTPATH)
		) as TEMPREPORTPATH
FROM [c10_audit].[dbo].[COGIPF_RUNREPORT]

WHERE COGIPF_REPORTPATH LIKE '%Nova Scotia Community College%'
AND  [COGIPF_REPORTNAME] NOT LIKE'%adHocReport%'
AND  [COGIPF_REPORTNAME] NOT LIKE '%analysis%'
) a