SELECT 
      CAST(UL.COGIPF_USERID AS VARCHAR(200)) AS RAN_BY_USERNAME,
      SUBSTRING(REPORT_NAME,CHARINDEX(CHAR(39),REPORT_NAME) +1,((CHARINDEX(CHAR(93),REPORT_NAME)-2) -(CHARINDEX(CHAR(39),REPORT_NAME)))) AS REPORTNAME,
      SUBSTRING(TEMPSUBJECT,CHARINDEX(CHAR(39),TEMPSUBJECT) +1,(charindex(char(93),TEMPSUBJECT,2))-(CHARINDEX(CHAR(39),TEMPSUBJECT) +2)) AS SUBJECT,
      SUBSTRING(TEMPREPORTPATH,1,((CHARINDEX(CHAR(39),TEMPREPORTPATH)-1))) as REPORTPATH,
      [START_DATE],
      START_TIME,
      TASK,
      TASK_RUNTIME,
      RESULT        
FROM
    (
     SELECT
     cast(RR.COGIPF_REPORTNAME as varchar(200)) AS REPORT_NAME,
     CAST(SUBSTRING(RR.COGIPF_REPORTPATH,PATINDEX('%]/folder%' ,COGIPF_REPORTPATH),PATINDEX('%]/folder%' ,COGIPF_REPORTPATH)) AS VARCHAR(100)) AS TEMPSUBJECT,
     cast(SUBSTRING((Replace(COGIPF_REPORTPATH,''']/folder[@name=''','->')) ,(24),Len(COGIPF_REPORTPATH))as varchar(300)) as TEMPREPORTPATH,
     P.COGIPF_OPERATION AS TASK,
     CONVERT(VARCHAR(10),RR.COGIPF_LOCALTIMESTAMP,101)  AS [START_DATE],
     CONVERT(VARCHAR(10),RR.COGIPF_LOCALTIMESTAMP,108)  AS [START_TIME],
     RR.COGIPF_SESSIONID,
     RR.COGIPF_STATUS AS RESULT,
     RR.COGIPF_RUNTIME AS TASK_RUNTIME
     FROM c10_audit.dbo.COGIPF_RUNREPORT  AS RR
     INNER JOIN c10_audit.dbo.COGIPF_PARAMETER AS P ON RR.COGIPF_REQUESTID = P.COGIPF_REQUESTID
      where p.COGIPF_OPERATION ='Execute'
      AND  p.COGIPF_OPERATION !=''
      AND  [COGIPF_REPORTNAME] NOT LIKE'%adHocReport%'
      AND  [COGIPF_REPORTNAME] NOT  Like'%View%'
      AND  [COGIPF_REPORTNAME] NOT  Like '%Analysis%'
      AND COGIPF_REPORTPATH LIKE '%Nova Scotia Community College%'
     ) as R2015COG
INNER JOIN c10_audit.dbo.COGIPF_USERLOGON AS UL ON R2015COG.COGIPF_SESSIONID = UL.COGIPF_SESSIONID
where  [COGIPF_USERNAME] NOT IN ('','not available')
  and [COGIPF_USERID] NOt IN ('','null')